package com.vyrriox.lauramod.client.gui.kawaii;

import com.vyrriox.lauramod.entity.Emote;
import com.vyrriox.lauramod.entity.LauraJob;
import com.vyrriox.lauramod.entity.Mood;
import com.vyrriox.lauramod.entity.brain.Needs;
import com.vyrriox.lauramod.entity.work.ChestPurpose;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;

/**
 * Icons of {@code textures/gui/kawaii_icons.png}: a 16 by 16 grid of 16 pixel icons, filled row by
 * row in the order of this enum (the atlas is generated by tools/generate_assets.py, which reads this
 * file to keep the same order). A few icons are drawn as vanilla items, see {@link #item()}.
 *
 * @author vyrriox
 */
public enum Icon {
    // row 0: tabs
    TAB_HOME, TAB_ORDERS, TAB_EMOTES, TAB_WORK, TAB_FETCH, TAB_STYLE, TAB_SETTINGS, TAB_INFO,
    BACKPACK, SPARE_0_9, SPARE_0_10, SPARE_0_11, SPARE_0_12, SPARE_0_13, SPARE_0_14, SPARE_0_15,
    // row 1: needs and stats
    NEED_HUNGER, NEED_ENERGY, NEED_FUN, NEED_ATTENTION, NEED_HYGIENE, HEALTH, AFFECTION, DESIRE,
    DAYS, SPARE_1_9, SPARE_1_10, SPARE_1_11, SPARE_1_12, SPARE_1_13, SPARE_1_14, SPARE_1_15,
    // row 2: moods
    MOOD_HAPPY, MOOD_IN_LOVE, MOOD_NEUTRAL, MOOD_BORED, MOOD_HUNGRY, MOOD_TIRED, MOOD_SAD, MOOD_ANGRY,
    MOOD_JEALOUS, MOOD_SULKING, SPARE_2_10, SPARE_2_11, SPARE_2_12, SPARE_2_13, SPARE_2_14, SPARE_2_15,
    // row 3: interface
    CLOSE, PREV, NEXT, PENCIL, CHECK, PLUS, MINUS, TRASH,
    UPLOAD, REFRESH, SPARKLE, HEART_FULL, HEART_HALF, HEART_EMPTY, STAR, LOCK,
    // row 4: orders
    FOLLOW, STAY, WANDER, COME, GO_HOME, SET_HOME, SLEEP, WAKE,
    STOP, HUG, KISS, COMPLIMENT, INVENTORY, EAT, UNGAG, QUEUE,
    // row 5: jobs and chest purposes
    JOB_LUMBERJACK, JOB_FARMER, JOB_COOK, CHEST, CHEST_WOOD, CHEST_HARVEST, CHEST_SEEDS, CHEST_INGREDIENTS,
    CHEST_FUEL, CHEST_MEALS, CHEST_PANTRY, CHEST_STORAGE, SKIN, MODEL, CALL, PICKUP,
    // row 6 and 7: emotes
    EMOTE_WAVE, EMOTE_CLAP, EMOTE_DANCE, EMOTE_LAUGH, EMOTE_CRY, EMOTE_BLUSH, EMOTE_FACEPALM, EMOTE_JUMP,
    EMOTE_BOW, EMOTE_THINK, EMOTE_SHRUG, EMOTE_STOMP, EMOTE_YAWN, EMOTE_CELEBRATE, EMOTE_SNAP, EMOTE_TWIRL,
    EMOTE_HUM, EMOTE_STRETCH, EMOTE_TAP_FOOT, EMOTE_BLOW_KISS, EMOTE_SNEEZE, EMOTE_HAIR_FLIP, EMOTE_CHECK_NAILS, EMOTE_AIR_GUITAR,
    EMOTE_HICCUP, EMOTE_POUT, EMOTE_SHIVER, EMOTE_FAN, EMOTE_HUG, EMOTE_KISS, COMBAT_PASSIVE, COMBAT_FIGHT;

    public final int u;
    public final int v;

    Icon() {
        this.u = (ordinal() % 16) * 16;
        this.v = (ordinal() / 16) * 16;
    }

    private ItemStack item;

    /**
     * Icons shown as a vanilla item instead of an atlas sprite (tools, blocks, food): they read
     * better as the real thing, and they follow resource packs.
     */
    public ItemStack item() {
        if (item == null) {
            Item i = switch (this) {
                case JOB_LUMBERJACK -> Items.IRON_AXE;
                case JOB_FARMER -> Items.IRON_HOE;
                case JOB_COOK -> Items.SMOKER;
                case CHEST -> Items.CHEST;
                case CHEST_WOOD -> Items.OAK_LOG;
                case CHEST_HARVEST -> Items.WHEAT;
                case CHEST_SEEDS -> Items.WHEAT_SEEDS;
                case CHEST_INGREDIENTS -> Items.BEEF;
                case CHEST_FUEL -> Items.COAL;
                case CHEST_MEALS -> Items.BREAD;
                case CHEST_PANTRY -> Items.CAKE;
                case CHEST_STORAGE -> Items.BARREL;
                case SKIN -> Items.PINK_DYE;
                case MODEL -> Items.ARMOR_STAND;
                case CALL -> Items.BELL;
                case PICKUP -> Items.HOPPER;
                default -> Items.AIR;
            };
            item = new ItemStack(i);
        }
        return item;
    }

    public static Icon mood(Mood mood) {
        return switch (mood) {
            case HAPPY -> MOOD_HAPPY;
            case IN_LOVE -> MOOD_IN_LOVE;
            case NEUTRAL -> MOOD_NEUTRAL;
            case BORED -> MOOD_BORED;
            case HUNGRY -> MOOD_HUNGRY;
            case TIRED -> MOOD_TIRED;
            case SAD -> MOOD_SAD;
            case ANGRY -> MOOD_ANGRY;
            case JEALOUS -> MOOD_JEALOUS;
            case SULKING -> MOOD_SULKING;
        };
    }

    public static Icon need(Needs.Need need) {
        return switch (need) {
            case HUNGER -> NEED_HUNGER;
            case ENERGY -> NEED_ENERGY;
            case FUN -> NEED_FUN;
            case ATTENTION -> NEED_ATTENTION;
            case HYGIENE -> NEED_HYGIENE;
        };
    }

    public static Icon job(LauraJob job) {
        return switch (job) {
            case LUMBERJACK -> JOB_LUMBERJACK;
            case FARMER -> JOB_FARMER;
            case COOK -> JOB_COOK;
            case NONE -> STOP;
        };
    }

    public static Icon chest(ChestPurpose purpose) {
        return switch (purpose) {
            case WOOD -> CHEST_WOOD;
            case HARVEST -> CHEST_HARVEST;
            case SEEDS -> CHEST_SEEDS;
            case INGREDIENTS -> CHEST_INGREDIENTS;
            case FUEL -> CHEST_FUEL;
            case MEALS -> CHEST_MEALS;
            case PANTRY -> CHEST_PANTRY;
            case STORAGE -> CHEST_STORAGE;
        };
    }

    public static Icon emote(Emote emote) {
        try {
            return valueOf("EMOTE_" + emote.name());
        } catch (IllegalArgumentException e) {
            return SPARKLE;
        }
    }
}
