org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant
neo_version=21.1.65
mod_id=lauramod
mod_name=My Girlfriend Laura
mod_license=All Rights Reserved
mod_version=1.1.0
mod_group_id=com.vyrriox.lauramod
mod_authors=vyrriox
mod_description=A companion mod adding Laura to the game.
