modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/laforetbrut/mods-mc-laura/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/laforetbrut/mods-mc-laura"
logoFile="lauramod_logo.png"
authors="${mod_authors}"
credits="Created by vyrriox"
description='''${mod_description}'''

# NeoForge 47.1 loads under the mod id "forge".
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
