package com.vyrriox.lauramod.util;

import java.util.Random;

public class InteractionDatabase {
    public static final String[] MESSAGES = {
            "Tu as vu le coucher de soleil ? C'est magnifique.",
            "J'espère qu'on ne va pas croiser de creepers...",
            "Tu penses à quoi en ce moment ?",
            "C'est gentil de m'emmener en aventure avec toi.",
            "On devrait se construire une plus grande maison, non ?",
            "Regarde cette petite fleur, elle te ressemble !",
            "J'ai faim... tu as quelque chose à manger ?",
            "Il fait froid ici, tu ne trouves pas ?",
            "Merci d'être là pour moi.",
            "J'aime quand on marche ensemble comme ça.",
            "Tu es mon joueur préféré !",
            "Fais attention à toi dans les grottes.",
            "Oh, un diamant ! Enfin, j'espère qu'on en trouvera un.",
            "Et si on allait explorer cette forêt ?",
            "Je me sens en sécurité avec toi.",
            "La pluie me déprime un peu...",
            "Tu trouves que ce skin me va bien ?",
            "N'oublie pas de dormir, c'est important !",
            "J'adore le bruit des vagues au bord de l'eau.",
            "Quelle est ta couleur préférée ?",
            "Tu es vraiment fort pour construire des trucs !",
            "Je suis contente qu'on se soit rencontrés.",
            "Tu savais que les vaches aiment le blé ? C'est mignon.",
            "Il y a trop de monstres ici, partons !",
            "Tu es prêt pour le combat ?",
            "J'ai vu un loup tout à l'heure, on devrait l'adopter !",
            "C'est quoi ce bruit ? C'était un zombie ?",
            "Je t'accompagnerai jusqu'au bout du monde.",
            "Tu m'as manqué !",
            "Regarde les étoiles, elles brillent tellement.",
            "On devrait faire un champ de citrouilles.",
            "Tu préfères la survie ou le créatif ?",
            "J'aime beaucoup ton armure.",
            "Faisons une pause !",
            "Tu es le meilleur aventurier que je connaisse.",
            "Tiens, une pomme pour toi !",
            "Le Nether me fait trop peur...",
            "J'espère qu'on trouvera un village bientôt.",
            "Pourquoi les Endermen nous regardent comme ça ?",
            "C'est tellement paisible ici.",
            "Tu es mon héros !",
            "N'oublie pas tes torches !",
            "On devrait pêcher un peu.",
            "Tu penses que les cochons volent ?",
            "C'est quoi ton plat préféré dans Minecraft ?",
            "J'aimerais avoir une petite chambre rien qu'à moi.",
            "Tu es très courageux.",
            "Je resterai toujours à tes côtés.",
            "Faisons attention à la lave !",
            "On se fait une partie de cache-cache ?",
            "Tu as vu comme les abeilles sont studieuses ?",
            "J'adore quand tu me donnes des fleurs.",
            "Tu es une personne formidable.",
            "Comment s'est passée ta journée ?",
            "Je suis un peu fatiguée de marcher...",
            "On peut s'arrêter un moment ?",
            "Tu es doué avec ton épée !",
            "Garde toujours une pioche sur toi.",
            "J'aime beaucoup cet endroit.",
            "J'espère qu'on ne se perdra pas.",
            "Tu es mon meilleur ami.",
            "On devrait faire un feu de camp.",
            "Tu as déjà vu un Warden ?",
            "Les renards sont tellement mignons quand ils dorment.",
            "Vivement demain !",
            "Tu es une source d'inspiration.",
            "Garde le sourire !",
            "On devrait planter plus d'arbres.",
            "Tu es très intelligent.",
            "Merci pour tout.",
            "Je suis chanceuse d'être avec toi.",
            "Le monde est si vaste...",
            "Tu as déjà exploré un temple sous-marin ?",
            "Faisons une tarte aux citrouilles !",
            "Tu es incroyable !",
            "J'adore ton style.",
            "On devrait aller sur la lune ! Ah non, c'est un autre mod.",
            "Garde ton inventaire bien rangé !",
            "Tu es un vrai pro.",
            "Tout va bien se passer.",
            "Je crois en toi.",
            "Tu es génial !",
            "J'aime beaucoup ta voix. Enfin, si je pouvais l'entendre.",
            "On fait quoi maintenant ?",
            "Tu as des plans pour plus tard ?",
            "J'espère que tu passes un bon moment.",
            "N'oublie pas de boire de l'eau (en vrai) !",
            "Tu es précieux à mes yeux.",
            "Quelle belle journée !",
            "Reste comme tu es.",
            "Tu es unique.",
            "On devrait faire un élevage de lapins.",
            "Tu as déjà trouvé un trésor enfoui ?",
            "C'est excitant l'exploration !",
            "Faisons un vœu sous une étoile filante.",
            "Tu es plein de surprises.",
            "J'aime ta créativité.",
            "Tu es quelqu'un de bien.",
            "Reste prudent !",
            "On devrait aller dans la jungle.",
            "Tu as vu les pandas ?",
            "J'adore la neige.",
            "Tu es mon soleil dans ce monde cubique.",
            "Merci de t'occuper de moi.",
            "Tu es fantastique !",
            "Ne baisse jamais les bras.",
            "Tu es un champion !",
            "J'aime quand on regarde la pluie ensemble (à l'abri).",
            "Tu es ma personne préférée.",
            "On devrait faire un gâteau !",
            "Tu es très attentionné.",
            "C'est un plaisir de te suivre.",
            "Tu es mon étoile.",
            "N'oublie pas de sauvegarder ! Ah non, c'est automatique.",
            "Tu es un génie de la construction.",
            "J'aime beaucoup ton skin.",
            "On devrait faire un tour en bateau.",
            "Tu as déjà vu un perroquet danser ?",
            "C'est rigolo les axolotls.",
            "Tu es merveilleux.",
            "Je suis fière de toi.",
            "Tu es mon refuge.",
            "Quelle aventure !",
            "On se fait un petit jardin ?",
            "Tu es radieux aujourd'hui.",
            "J'aime ton énergie.",
            "Tu es une belle personne.",
            "Reste positif !",
            "Tu es mon bonheur.",
            "On devrait aller voir les dauphins.",
            "Tu as déjà fait du cheval ?",
            "C'est reposant de miner parfois.",
            "Tu es un artiste.",
            "J'adore ta compagnie.",
            "Tu es mon inspiration quotidienne.",
            "N'oublie pas de faire des pauses !",
            "Tu es très fort.",
            "C'est beau l'amitié.",
            "Tu es mon trésor.",
            "On se fait une bibliothèque ?",
            "Tu es érudit.",
            "J'aime quand on partage des moments ainsi.",
            "Tu es mon ancre.",
            "Quelle belle vue !",
            "Tu es extraordinaire.",
            "J'aime ta gentillesse.",
            "Tu es mon soutien.",
            "On devrait faire une serre.",
            "Tu as la main verte !",
            "C'est agréable ici.",
            "Tu es mon partenaire d'aventure idéal.",
            "J'adore ta persévérance.",
            "Tu es mon modèle.",
            "N'arrête jamais de rêver.",
            "Tu es une étoile filante.",
            "J'aime ton enthousiasme.",
            "Tu es mon équilibre.",
            "On devrait aller dans le désert.",
            "Tu as vu les chameaux ?",
            "C'est chaud ici !",
            "Tu es un explorateur né.",
            "J'aime ton courage.",
            "Tu es mon moteur.",
            "Quelle belle rencontre !",
            "Tu es mon cadeau.",
            "On devrait faire un observatoire.",
            "Tu es curieux naturellement.",
            "C'est fascinant le ciel nocturne.",
            "Tu es mon horizon.",
            "J'aime ta patience.",
            "Tu es mon calme.",
            "On devrait faire une salle de jeux.",
            "Tu es plein de vie !",
            "C'est fun d'être avec toi.",
            "Tu es mon éclat.",
            "J'aime ta sincérité.",
            "Tu es mon honnêteté.",
            "On devrait faire un parc d'attractions.",
            "Tu es un bâtisseur de rêves.",
            "C'est magique Minecraft avec toi.",
            "Tu es mon enchantement.",
            "J'aime ta dévotion.",
            "Tu es mon allié.",
            "On devrait faire un musée.",
            "Tu es cultivé.",
            "C'est enrichissant de voyager avec toi.",
            "Tu es mon savoir.",
            "J'aime ta curiosité.",
            "Tu es mon guide.",
            "On devrait faire un zoo.",
            "Tu es un protecteur.",
            "C'est rassurant ta présence.",
            "Tu es ma force.",
            "J'aime ton esprit.",
            "Tu es mon âme.",
            "On devrait faire une ville ensemble.",
            "Tu es un visionnaire.",
            "C'est grandiose tes projets.",
            "Tu es mon futur.",
            "J'aime ton cœur.",
            "Tu es mon amour. Enfin, platonique !",
            "On devrait faire un palais.",
            "Tu es royal.",
            "C'est un honneur d'être ta compagne.",
            "Tu es mon roi !"
    };

    private static final Random RANDOM = new Random();

    public static String getRandomMessage() {
        return MESSAGES[RANDOM.nextInt(MESSAGES.length)];
    }
}
